// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, user_id, title, body, tags, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW(), NOW())
RETURNING id, user_id, title, body, mood, ai_analysis, tags, created_at, updated_at
`

type CreateEntryParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Tags   []string  `json:"tags"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.UserID,
		arg.Title,
		arg.Body,
		pq.Array(arg.Tags),
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Mood,
		&i.AiAnalysis,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1 AND user_id = $2
`

type DeleteEntryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, arg.ID, arg.UserID)
	return err
}

const getEntriesByUserID = `-- name: GetEntriesByUserID :many
SELECT id, user_id, title, body, mood, ai_analysis, tags, created_at, updated_at FROM entries WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetEntriesByUserID(ctx context.Context, userID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Mood,
			&i.AiAnalysis,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, user_id, title, body, mood, ai_analysis, tags, created_at, updated_at FROM entries WHERE id = $1 AND user_id = $2
`

type GetEntryByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEntryByID(ctx context.Context, arg GetEntryByIDParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Mood,
		&i.AiAnalysis,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntryAIAnalysis = `-- name: UpdateEntryAIAnalysis :one
UPDATE entries SET ai_analysis = $1, mood = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, user_id, title, body, mood, ai_analysis, tags, created_at, updated_at
`

type UpdateEntryAIAnalysisParams struct {
	AiAnalysis sql.NullString `json:"ai_analysis"`
	Mood       sql.NullString `json:"mood"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateEntryAIAnalysis(ctx context.Context, arg UpdateEntryAIAnalysisParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntryAIAnalysis, arg.AiAnalysis, arg.Mood, arg.ID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Mood,
		&i.AiAnalysis,
		pq.Array(&i.Tags),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
